### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Bananeweizen** [CROSSINGTUD/CogniCrypt#205] opened 2018-08-05 12:37 UTC
**Describe the bug**
CME in Cognicrypt while opening projects and building the Eclipse platform.ui workspace.

**To Reproduce**
Not reproducable by simple procedures (but that is the nature of CME).

**Additional context**
CogniCrypt Crypto-API Misuse Detector	1.0.0.201807051636	
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at soot.SootResolver.bringToSignaturesUnchecked(SootResolver.java:285)
	at soot.SootResolver.bringToSignatures(SootResolver.java:278)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:158)
	at soot.SootResolver.resolveClass(SootResolver.java:137)
	at soot.Scene.loadClass(Scene.java:861)
	at soot.Scene.loadClassAndSupport(Scene.java:847)
	at soot.Scene.loadNecessaryClasses(Scene.java:1602)
	at de.cognicrypt.staticanalyzer.sootbridge.SootRunner.setSootOptions(SootRunner.java:126)
	at de.cognicrypt.staticanalyzer.sootbridge.SootRunner.runSoot(SootRunner.java:98)
	at de.cognicrypt.staticanalyzer.handlers.AnalysisKickOff$1.run(AnalysisKickOff.java:87)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Comment by johspaeth** [comment] 2018-08-14 13:39
Thanks for the bug report.  It seems to be a problem with the [soot](https://github.com/Sable/soot/) setup of one of your projects in the workspace.

Without knowing the nature of the project(s) in your workspace, it is difficult to understand the issue further. What do you mean by the platform.ui workspace? Can you share your workspace, i.e., can you reproduce it on an open source project/workspace?

**Comment by Bananeweizen** [comment] 2018-08-17 06:38
I've checked out this repository: https://github.com/eclipse/eclipse.platform.ui and imported all projects (excluding nested test bundles). I've not set any workspace preferences or project properties for CogniCrypt. I have only installed and run it (on all projects of the workspace). Basically I was just doing an initial evaluation to see what kind of warnings I might see with CogniCrypt after watching the Eclipse.org channel Youtube video about it.

**Comment by adnan904** [comment] 2018-08-28 14:15
OS: Windows 10
Eclipse Version: Oxygen.3a Release (4.7.3a)
Java Version: Oracle 1.8.0_172

**To Reproduce**:

After running the StaticAnalyzer, I imported some of the projects from eclipse.platform.ui repository, closed all of them and opened the below listed projects at the same time to reproduce the error: 

- eclipse.platform.ui
- org.eclipse.core.databinding
- org.eclipse.core.databinding.beans
- org.eclipse.core.databinding.observable
- org.eclipse.core.databinding.property
- org.eclipse.e4.ui.css.core
- org.eclipse.e4.ui.css.swt
 
Unfortunately it's very random behaviour and doesn't reproduce the error all the times. But I have been able to reproduce the error 4 times and each time I closed the projects in the workspace and randomly opened couple of them at the same time.
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at soot.SootResolver.bringToSignaturesUnchecked(SootResolver.java:285)
	at soot.SootResolver.bringToSignatures(SootResolver.java:278)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:158)
	at soot.SootResolver.resolveClass(SootResolver.java:137)
	at soot.Scene.tryLoadClass(Scene.java:831)
	at soot.Scene.loadBasicClasses(Scene.java:1504)
	at soot.Scene.loadNecessaryClasses(Scene.java:1587)
	at de.cognicrypt.staticanalyzer.sootbridge.SootRunner.setSootOptions(SootRunner.java:126)
	at de.cognicrypt.staticanalyzer.sootbridge.SootRunner.runSoot(SootRunner.java:98)
	at de.cognicrypt.staticanalyzer.handlers.AnalysisKickOff$1.run(AnalysisKickOff.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by johspaeth** [comment] 2018-08-28 14:32
It could be a problem as we execute Soot multiple times on different projects. Soot internally holds its Scene in a Singleton (static field) which might cause problems here.

Could you try to add a call to:
`Scene.v().reset();` before running soot (e.g., [here](https://github.com/CROSSINGTUD/CogniCrypt/blob/8158b6fa90c07eaca0c8249938212ca499ed4f8e/plugins/de.cognicrypt.staticanalyzer/src/de/cognicrypt/staticanalyzer/sootbridge/SootRunner.java#L107)).

If that doesn't solve the problem yet, please try to block the execution of soot on multiple projects at the same time, queue the projects for instance, and see if it fixes the problem.

**Comment by adnan904** [comment] 2018-10-18 13:17
@Bananeweizen Can you please check again if the problem still persists? We have tried to fix it and can no longer reproduce it. So if you can check if it is fixed on your side will be highly appreciated.

**Closed** 2018-10-25 14:34 UTC
Labels: Analysis, bug

**Comment by Bananeweizen** [comment] 2018-10-29 09:42
Sorry, I don't even have that installation available anymore. Therefore I cannot easily reproduce the old issue.
